---
abstract: 'ShipIt step to announce the upload on Facebook'
author:
  - 'Kazuhiro Osawa <yappo {at} shibuya {dot} pl>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ShipIt-Step-Facebook
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  ShipIt: 0
  YAML: 0
resources:
  homepage: http://github.com/yappo/p5-ShipIt-Step-Faebook/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/p5-ShipIt-Step-Faebook.git
version: 0.01
